service: gitlab-cicd-tutorial

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage}
  region: ${opt:region}
  memorySize: 256
  timeout: 30
  
functions:
  hello:
    handler: src/hello.lambda_handler
    events:
      - http:
          path: hello
          method: get
          cors: true
